name = "edmaguro"
main = "src/index.ts"
compatibility_date = "2023-01-22"
send_metrics = false

routes = [
  { pattern = "edmagu.ro/*", zone_id = "79c1e3c75f305e5eb3bd174a577fd68d" },
]

[vars]
_ = "Dummy value to always generate Env interface"
