name = "edmaguro"
main = "src/index.ts"
compatibility_date = "2023-08-01"
send_metrics = false

routes = [
  { pattern = "edmagu.ro", zone_id = "63edc8cce616f1c5923233c3d90179ca", custom_domain = true },
  { pattern = "edmagu.ro/*", zone_id = "63edc8cce616f1c5923233c3d90179ca" },
]

[placement]
mode = "smart"

[vars]
_ = "Dummy value to always generate Env interface"
