name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  hygiene:
    name: Hygiene

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.ignorecase false

      - name: Checkout tree
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set-up Node.js LTS
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          check-latest: true

      - run: corepack enable

      # Dependencies
      - run: yarn install --immutable

      # CI checks with Biome
      - run: yarn ci

  build-and-test:
    name: Build and Test

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set-up Node.js LTS
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          check-latest: true

      - run: corepack enable

      # Dependencies
      - run: yarn install --immutable

      # Run the testsuite
      - run: yarn test

      # Build
      - run: yarn build
