name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  hygiene:
    name: Hygiene

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.ignorecase false

      - name: Checkout tree
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set-up Node.js LTS
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: lts/*
          check-latest: true

      - run: corepack enable

      # Dependencies
      - run: yarn install --immutable

      # CI checks with Biome
      - run: yarn lint

  build-and-test:
    name: Build and Test

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set-up Node.js LTS
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: lts/*
          check-latest: true

      - run: corepack enable

      # Dependencies
      - run: yarn install --immutable

      # Run the testsuite
      - run: yarn test

      # Build
      - run: yarn build

  deploy:
    name: Deploy Worker

    if: github.event_name == 'push' && github.ref_name == 'main'

    needs:
      - hygiene
      - build-and-test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set-up Node.js LTS
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: lts/*
          check-latest: true

      - run: corepack enable

      # Dependencies
      - run: yarn install --immutable

      # Build
      - run: yarn build

      # Deploy
      - run: yarn deploy
        working-directory: apps/edmaguro
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
