name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  hygiene:
    name: Hygiene

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set-up Node.js LTS
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: lts/*
          check-latest: true

      - run: corepack enable

      # Dependencies
      - run: yarn install --immutable

      # Check formatting with prettier
      - run: yarn format:check

      # Linting with eslint
      - run: yarn lint

  build-and-test:
    name: Build and Test

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set-up Node.js LTS
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: lts/*
          check-latest: true

      - run: corepack enable

      # Dependencies
      - run: yarn install --immutable

      # Run the testsuite
      - run: yarn test

      # Build
      - run: yarn build
